### ISSUE TITLE
Make build folder assignable from launch.json

### ISSUE THREAD

**Issue by 88plug** [NewSpring/meteor-launch#30]
-----------------
[16:13:11]: --- Step: gym ---
[16:13:11]: -----------------
[16:13:11]: Installing provisioning profile...
[16:13:11]: xcrun xcodebuild -list -project /Users//Desktop/XXXXXX/.meteor/local/cordova-build/platforms/ios/XXXXX.xcodeproj
[16:10:08]: xcodebuild -list timed-out after 10 seconds. You might need to recreate the user schemes. You can override the timeout value with the environment variable FASTLANE_XCODE_LIST_TIMEOUT

I increased the timeout to 320 and it still wont budge.    Got all green before this - 
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/junit_generator.rb:17:in `write': [!] No such file or directory - /Users/XXXXX/Desktop/XXXXXproject/.build/ios/report.xml (Errno::ENOENT)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/junit_generator.rb:17:in `generate'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/lane_manager.rb:73:in `finish_fastlane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/lane_manager.rb:63:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/commands_generator.rb:244:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
Command failed: fastlane ios beta

No such file or directory - /Users/XXX/Desktop/XXXproject/.build/ios/report.xml (Errno::ENOENT)

**Comment by 88plug** [comment]
Seems your using .build/ios/report.xml instead of the location I set for my directory - which isn't that!

**Comment by johnthepink** [comment]
Ah yes. Right now you have to use the `.build` directory. So `.build/ios/project/NameOfYourApp.xcodeproj` for the `XCODE_PROJECT` variable, replacing NameOfYourApp with the name of your app from the `mobile-config.js` file. Let me know if that works for you.

I intend to make the build directory assignable from `launch.json`, but I haven't implemented that yet. Sorry that is confusing right now.

I'm going to change the name of this issue and leave it open so we can implement this. Thanks!

**Comment by johnthepink** [comment]
@88plug I think the dynamic build folders might be part of a larger change involving switching out the variables for different names entirely. Until I implement that, I have published 0.2.6 via #33. I think it makes everything a little less confusing.

After upgrading, you can remove `XCODE_PROJECT` and `ANDROID_BUILD_FOLDER` from your `launch.json`. Everything will now automatically map to the `.build` directory.

**Comment by 88plug** [comment]
I updated and now I get

xcodebuild -list timed-out after 90 seconds. You might need to recreate the user schemes. You can override the timeout value with the environment variable FASTLANE_XCODE_LIST_TIMEOUT

+------+-----------------------------------------+-------------+
|                       fastlane summary                       |
+------+-----------------------------------------+-------------+
| Step | Action                                  | Time (in s) |
+------+-----------------------------------------+-------------+
| 1    | Verifying required fastlane version     | 0           |
| 2    | default_platform                        | 0           |
| 3    | Switch to ios build_app_production lane | 0           |
| 4    | sigh                                    | 5           |
| 5    | update_project_provisioning             | 0           |
| 6    | gym                                     | 90          |
| 7    | slack                                   | 1           |
+------+-----------------------------------------+-------------+

[01:52:45]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Adding Application Services/Entitlements
   https://github.com/fastlane/fastlane/issues/90 [closed] 3 💬
   03 Sep 2015

➡️  `jira` action gem verification bug fixed
   https://github.com/fastlane/fastlane/pull/4719 [closed] 5 💬
   5 weeks ago


[!] xcodebuild -list timed-out after 90 seconds. You might need to recreate the user schemes. You can override the timeout value with the environment variable FASTLANE_XCODE_LIST_TIMEOUT
Command failed: fastlane ios beta

How long do I need here?

**Comment by 88plug** [comment]
tried even 500 seconds - no go.  Can't get past this step...

**Comment by johnthepink** [comment]
I have seen this before. `xcrun xcodebuild -list` will time out if it hasn't been opened before. So, launch actually tries to open the project in Xcode so that the schemes get built, preventing `xcrun xcodebuild -list` from timing out.

1. Does Xcode open for you after running `launch build`?
2. What happens if you run `xcrun xcodebuild -list -project path/to/your/project.xcodeproj`?

**Comment by 88plug** [comment]
To answer your questions :

#1 - Yes using sudo launch build testflight will pop xcode
#2 - Nothing?  I get some output but there is really no activity on the cpu and xcodebuild process

xcrun xcodebuild -list -project .build/ios/project/XXXproject.xcodeproj
Information about project "XXXproject":
    Targets:
        XXXproject

    Build Configurations:
        Debug
        Release

    If no build configuration is specified and -scheme is not passed then "Release" is used.

    Schemes:
        XXXproject
        CordovaLib

**Comment by johnthepink** [comment]
Hmm that looks correct. All it should do is list is the schemes.

Just to confirm, your process looks like this?

```shell
$ launch build myapp.com
$ launch testflight
```

And it still hangs on `xcrun xcodebuild -list`?

Would it be possible for you to share a redacted version of your `launch.json`?

**Comment by 88plug** [comment]
Then if I run a second time it sits here :
 Targets:
        XXXproject

    Build Configurations:
        Debug
        Release

    If no build configuration is specified and -scheme is not passed then "Release" is used.

**Comment by 88plug** [comment]
Just to confirm, your process looks like this?

$ launch build myapp.com
$ launch testflight

OK so xcode launches and I see waiting for xcodebuild, I saw some activity - but it's stalled.
https://www.evernote.com/l/AAbdLVuumD5CO6YC_g5FznfpC2WTll2BX1Y

{
  "XCODE_SCHEME_NAME": "Zoom",
  "APP_IDENTIFIER": "io.Zoom.Zoom",        
  "APPLE_ID": "x@Zoom.io",
  "FASTLANE_PASSWORD": "Zoom",
  "KEYCHAIN_PASSWORD": "Zoom",
  "CERT_KEY_PATH": "./Zoom.p12",
  "CERT_PASSWORD": "Zoom",
  "SLACK_URL": "https://hooks.slack.com/services/Zoom/Zoom/Zoom",
  "SLACK_ROOM": "#Zoom",
  "FASTLANE_XCODE_LIST_TIMEOUT": "1200"
}

**Comment by johnthepink** [comment]
Is it still timing out for you? What does your `mobile-config.js` look like?

**Comment by johnthepink** [comment]
@88plug just published `0.3.0` which brings support for a custom input directory and a custom output directory. Let me know if that helps!
